const menu = [
    {
        icon:'pie-chart',
        title:'列表',
        path:'list',
        index:1
    },
    {
        icon:'desktop',
        title:'姐荤',
        path:'marry',
        index:2
    },
    {
        icon:'inbox',
        title:'标题3',
        path:'path3',
        index:3
    },
    {
        icon:'mail',
        title:'标题4',
        path:'path4',
        index:4,
        submenu:[
            {
                title:'标题5',
                path:'path5',
                index:5
            },
            {
                title:'标题6',
                path:'path6',
                index:6
            },
        ]
    },
    {
        icon:'mail',
        title:'标题7',
        path:'path7',
        index:7,
        submenu:[
            {
                title:'标题8',
                path:'path8',
                icon:'mail',
                index:8
            },
            {
                title:'标题9',
                path:'path9',
                icon:'mail',
                index:9
            },
            {
                title:'标题10',
                path:'path10',
                icon:'mail',
                index:10,
                submenu:[
                    {
                        title:'标题11',
                        path:'path11',
                        icon:'mail',
                        index:11
                    },
                    {
                        title:'标题12',
                        path:'path12',
                        icon:'mail',
                        index:12,
                        submenu:[
                            {
                                title:'标题13',
                                path:'path13',
                                icon:'mail',
                                index:13,
                            },
                            {
                                title:'标题14',
                                path:'path14',
                                icon:'mail',
                                index:14,
                            }
                        ]
                    },
                ]
            },
        ]
    }
]
export default menu;